# Generated by Django 2.2.10 on 2020-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginManage',
            fields=[
                ('plugin_num', models.CharField(max_length=50)),
                ('plugin_belong_net', models.CharField(max_length=50)),
                ('plugin_name', models.CharField(max_length=50)),
                ('plugin_status', models.CharField(max_length=50)),
                ('produce', models.CharField(max_length=50)),
            ],
        ),
    ]
